### PR TITLE
Add `num_cpu` and `available_memory` steps

### PR DESCRIPTION
**Pull request by rh-tguittet**
## Changes introduced with this PR

Introduces two new steps:
- `num_cpu`: returns the number of logical CPUs
- `available_memory`: returns the amount of available (free) memory in bytes

I plan on using those values to adjust the parallelism setting for foreach loops.

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Review by jaredoconnell — APPROVED** [review]
Seems like the right place to put this. Thanks for the contribution!

**Comment by dustinblack** [comment]
This seems fine, but I do wonder if it would make more sense to expand both the CPU and memory cases to return detailed information about both, from which you can pull the specific information you are interested it. It seems a little strange to implement these steps specifically for the number of logical CPUs and the available memory. We also do already have the separate [metadata plugin](https://github.com/arcalot/arcaflow-plugin-metadata), which arguably already returns this information via Ansible's gather facts (though perhaps right now we only return total memory and not available memory there).

**Comment by rh-tguittet** [comment]
I wasn't aware of this metadata plugin... and it pretty much covers my use case here. Feel free to close this.

**Comment by jaredoconnell** [comment]
Ah. I forgot about that plugin. Using os calls would likely be more lightweight than ansible facts, but it likely makes sense to stick with the metadata plugin.

**Comment by rh-tguittet** [comment]
The utilities plugin has this feature, closing this to avoid duplicate efforts.

**Pull request closed without merging**
